### ISSUE TITLE
Question: mpv command

### ISSUE THREAD

**Issue by aliveupstairs** [LiteracyFanatic/twist-cli#1]
https://github.com/LiteracyFanatic/twist-cli/blob/4f473aa28be3cfead8c7683718e34a49cb8c3cca/Program.fs#L229

I don't know how much of that code is F# and how much is `mpv`, but my question is how do you feed something like this URL `https://twistcdn.bunny.sh/anime/animehere/[ani-me] Ani Me - 01 [10bit  DVD 480p] [78d0F9BD].mp4` to `mpv`? what's the end result of `Arguments`?

Also, shouldn't [`dotnet`](https://www.archlinux.org/packages/community/x86_64/dotnet-runtime/) be listed as a dependency. Do I have to keep [`dotnet-runtime`](https://www.archlinux.org/packages/community/x86_64/dotnet-runtime/) to run `twist`?

**Comment by LiteracyFanatic** [comment]
That particular line generates the commandline arguments which are passed to mpv. Using the URL you provided, the generated command would look like this `
mpv --input-conf mpv-input.conf --http-header-fields="referer: https://twist.moe/" "https://twistcdn.bunny.sh/anime/animehere/[ani-me] Ani Me - 01 [10bit DVD 480p] [78d0F9BD].mp4"
` The `--input-conf mpv-input.conf` isn't strictly necessary, but it adds keyboard shortcuts to move backwards and forwards in the playlist. The referer header is important; the video will refuse to load without it.

As far as dependencies go, it is a bit complicated. `dotnet-sdk` is required to build `twist` from source. Whether or not `dotnet-runtime` is needed depends on how `twist` is built. There is an option to bundle the runtime into the binary. Personally, I do install the `dotnet-runtime` package and build twist as a "self-contained" binary, since the resulting binary is much smaller. This basically means it extracts itself and the files it requires to a temp directory and runs from there. I'm eventually planning to package it for Arch Linux, but the guidlines for packaging dotnet programs are still being developed. Things work the way they do now because `twist` used to need access to Node.js packages to execute some JavaScript to obtain a cookie it needed. twist.moe just made some changes to the website which make that irrelevant, so I will probably change that in the future.

Sorry for the somewhat rambly answer. Let me know if any of it needs clarification.

**Comment by aliveupstairs** [comment]
`~/.local/share/twist/animehere/completed` is used to track completed episodes?
how about the command get replaced with 
```fish
$ mpv --referrer="https://twist.moe/" --playlist=episodes
```
which works, using `mpv` to track watching state and nullifying the need for input configurations from `mpv-input.conf`?

**Comment by LiteracyFanatic** [comment]
I actually have a local branch investigating that scenario. The issue is that it doesn't support "finishing" a playlist. If you have 10 episodes, you will only ever be able to mark that you are on episode 10, not that you have completed episode 10. This is fine if you are watching a series which has already aired completely, but annoying if you are watching a weekly show since it will cause mpv to load an episode you already watched when a new one comes out. Of course you can just move to the next episode by pressing `>`, but I'd prefer `twist` to just load the right video in all cases. I will still likely switch to using the `--playlist` flag in a future update because it allows `--prefetch-playlist=yes` to be used which removes the need to wait for the next episode to load when the one you are watching finishes. I'll still need to track the number of episodes completed though to avoid the edge case I mentioned before.

**Comment by aliveupstairs** [comment]
I see your point. If it were a matter of pressing `>` it would be actually preferable because one might not always have finished the last episode and they can control if they want to move to the newly added episode. the problem is that if you actually finished the playlist, the progress would be removed as it is a finished playlist and that would be problematic for ongoing shows as you said. What I could think to mitigate this issue a file chooser coupled with [--playlist-start](https://mpv.io/manual/master/#options-playlist-start)
```
$ twist watch animehere
```
![image](https://user-images.githubusercontent.com/46059092/73130552-6b223800-3ffa-11ea-948c-6bfe536b4c90.png)

with the names taken from the URL which is well structured. an arrow up would reveal the last episode.
